#!/bin/sh
### BEGIN INIT INFO
# Provides:             phpr
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    phpr - Photo proxy
# Description:          phpr - Photo proxy with resizing and watermarks
### END INIT INFO

DAEMON=/usr/local/bin/phpr
RUNDIR=/run/phpr
PIDFILE=$RUNDIR/phpr.pid
CONFIGFILE=/etc/phpr/config.cfg
ARGS="-d -c=$CONFIGFILE -pid=$PIDFILE"
NAME="phpr"

test -x $DAEMON || exit 0

case "$1" in
    start)
        if start-stop-daemon --start --quiet --chuid phpr:phpr --make-pidfile --exec $DAEMON -- $ARGS
        then
            echo "$NAME started."
        else
            echo "$NAME starting failed."
        fi
        ;;
    stop)
        if start-stop-daemon --stop --retry forever/TERM/1 --quiet --make-pidfile --oknodo --pidfile $PIDFILE --exec $DAEMON
        then
            echo "$NAME stopped."
        else
            echo "$NAME stop failed"
        fi
        rm -f $PIDFILE
        sleep 1
        ;;
    restart)
        ${0} stop
        ${0} start
        ;;
    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
