#!/bin/sh
set -e

case "$1" in
  install)
    adduser --system --home /opt/ms-phpr/ --group phpr
    mkdir /opt/ms-phpr/
    mkdir /run/phpr
    chown -R phpr: /opt/ms-phpr/
    chown -R phpr: /run/phpr
    ;;

  upgrade)
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
